# Generated by Django 5.1.4 on 2025-01-31 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movieinfo_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieinfo',
            name='poster',
        ),
    ]
